### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by hqzh** [gerryli0214/vue-directives#5]
1、fun是基于什么考虑传字符串名字进去，我想这样v-throttoe="{fun:()=>clickFn(item)}"这样传参怎么处理呢？
2、是否考虑增加参数，参考lodash的指定调用在节流开始前还是节流后触发/指定在延迟开始前调用还是延迟结束后调用调用

**Comment by gerryli0214** [comment]
建议比较好，传参可以通过args参数传递，后续版本会完善这部分功能，谢谢！

**Comment by gerryli0214** [comment]
引入了debounce，增加了before、all修饰符，至于传参，格式没变
